-- Agent Capabilities Extension
ALTER TABLE agents ADD COLUMN IF NOT EXISTS cap_calendar     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS cal_link         TEXT    DEFAULT NULL;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS cap_leads        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS lead_fields      JSONB   NOT NULL DEFAULT '[]';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS lead_email       VARCHAR(255) DEFAULT NULL;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS cap_products     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS products_data    JSONB   NOT NULL DEFAULT '[]';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS cap_multilang    BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS cap_email        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS smtp_host        VARCHAR(255) DEFAULT NULL;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS smtp_port        INTEGER DEFAULT 587;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS smtp_user        VARCHAR(255) DEFAULT NULL;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS smtp_pass        VARCHAR(255) DEFAULT NULL;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS smtp_from        VARCHAR(255) DEFAULT NULL;

-- Lead captures table
CREATE TABLE IF NOT EXISTS lead_captures (
  id          SERIAL PRIMARY KEY,
  agent_id    INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  session_id  VARCHAR(64) NOT NULL,
  data        JSONB NOT NULL DEFAULT '{}',
  source      VARCHAR(20) NOT NULL DEFAULT 'web',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_leads_agent ON lead_captures(agent_id);
